//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Квартиры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Квартиры()
        {
            this.Сделки = new HashSet<Сделки>();
        }
    
        public int Код_квартиры { get; set; }
        public Nullable<int> Улица { get; set; }
        public string Номер_дома { get; set; }
        public string Номер_квартиры { get; set; }
        public string Площадь_квартиры { get; set; }
        public string Количество_комнат { get; set; }
        public Nullable<decimal> Цена_квартиры { get; set; }
    
        public virtual Улицы Улицы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сделки> Сделки { get; set; }
    }
}
