//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сделки
    {
        public int Код_сделки { get; set; }
        public Nullable<int> Код_квартиры { get; set; }
        public Nullable<int> Риэлтор { get; set; }
        public Nullable<int> Покупатель { get; set; }
        public Nullable<decimal> Цена_сделки { get; set; }
    
        public virtual Квартиры Квартиры { get; set; }
        public virtual Покупатели Покупатели { get; set; }
        public virtual Риэлторы Риэлторы { get; set; }
    }
}
